<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <!-- Эта строка принудительно загружает Window и другие теги -->
    <ImportDesktopWindowsTargeting>true</ImportDesktopWindowsTargeting>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="Xabe.FFmpeg" Version="6.0.2" />
    <Resource Include="fonts/Impact.ttf" />

  </ItemGroup>

</Project>
